[pytest]
asyncio_mode = strict
testpaths = 13_tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    asyncio: mark test as async
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning
    ignore:builtin type swigvarlink has no __module__ attribute
